version: "3.7"

services:
  # Message broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    mem_reservation: 300m
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - currency-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # Zipkin server
  zipkin-server:
    image: openzipkin/zipkin:2.23
    container_name: zipkin-server
    mem_reservation: 300m
    restart: always
    depends_on:
      - rabbitmq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    ports:
      - "9411:9411"
    networks:
      - currency-network

  # Naming server
  naming-server:
    image: sjm-naming-server:0.0.1-SNAPSHOT
    container_name: naming-server
    mem_reservation: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  # Api gateway
  api-gateway:
    image: sjm-api-gateway:0.0.1-SNAPSHOT
    container_name: api-gateway
    mem_reservation: 700m
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_RABBITMQ_HOST: rabbitmq
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    ports:
      - "8765:8765"
    networks:
      - currency-network

  # Currency exchange service
  currency-exchange:
    image: sjm-currency-exchange-service:0.0.1-SNAPSHOT
    container_name: currency-exchange.api
    mem_reservation: 700m
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_RABBITMQ_HOST: rabbitmq
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    ports:
      - "8000:8000"
    networks:
      - currency-network

  # Currency conversion service
  currency-conversion:
    image: sjm-currency-conversion-service:0.0.1-SNAPSHOT
    container_name: currency-conversion.api
    mem_reservation: 700m
    depends_on:
      - naming-server
      - rabbitmq
      - currency-exchange
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_RABBITMQ_HOST: rabbitmq
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    ports:
      - "8100:8100"
    networks:
      - currency-network

networks:
  currency-network:

volumes:
  rabbitmq_data: