apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
      - image: sjm-currency-conversion-service-kubernetes:0.0.2-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: sjm-currency-conversion-service-kubernetes
        readinessProbe:
          httpGet:
            port: 8100
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8100
            path: /actuator/health/liveness
        envFrom:
          - configMapRef:
              name: currency-conversion
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: currency-conversion
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
data:
  CURRENCY_EXCHANGE_SERVICE_URL: http://currency-exchange
metadata:
  name: currency-conversion
  namespace: default
